"""add source transaction and fact sales tables

Revision ID: 8598c49cd9d3
Revises: dfd50e6be323
Create Date: 2026-06-02 11:05:22.994584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8598c49cd9d3'
down_revision: Union[str, Sequence[str], None] = 'dfd50e6be323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_sales_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_no', sa.String(length=100), nullable=False),
    sa.Column('source_row_no', sa.String(length=50), nullable=True),
    sa.Column('source_row_hash', sa.String(length=255), nullable=False),
    sa.Column('order_no', sa.String(length=100), nullable=True),
    sa.Column('customer_code', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('item_group_code', sa.String(length=100), nullable=True),
    sa.Column('item_group_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('salesperson', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('item_weight', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unit_coefficient', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tonnes', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('pay_deal', sa.String(length=50), nullable=True),
    sa.Column('credit_mark', sa.String(length=50), nullable=True),
    sa.Column('invoice_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'source_type', 'source_row_hash', name='uq_fact_sales_lines_source_hash')
    )
    op.create_index(op.f('ix_fact_sales_lines_customer_code'), 'fact_sales_lines', ['customer_code'], unique=False)
    op.create_index(op.f('ix_fact_sales_lines_id'), 'fact_sales_lines', ['id'], unique=False)
    op.create_index(op.f('ix_fact_sales_lines_item_code'), 'fact_sales_lines', ['item_code'], unique=False)
    op.create_index(op.f('ix_fact_sales_lines_item_group_code'), 'fact_sales_lines', ['item_group_code'], unique=False)
    op.create_index(op.f('ix_fact_sales_lines_location'), 'fact_sales_lines', ['location'], unique=False)
    op.create_index(op.f('ix_fact_sales_lines_salesperson'), 'fact_sales_lines', ['salesperson'], unique=False)
    op.create_index(op.f('ix_fact_sales_lines_source_no'), 'fact_sales_lines', ['source_no'], unique=False)
    op.create_index(op.f('ix_fact_sales_lines_source_row_hash'), 'fact_sales_lines', ['source_row_hash'], unique=False)
    op.create_index(op.f('ix_fact_sales_lines_source_type'), 'fact_sales_lines', ['source_type'], unique=False)
    op.create_index(op.f('ix_fact_sales_lines_transaction_date'), 'fact_sales_lines', ['transaction_date'], unique=False)
    op.create_table('hansa_delivery_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('ser_nr', sa.String(length=100), nullable=False),
    sa.Column('order_nr', sa.String(length=100), nullable=True),
    sa.Column('ship_date', sa.Date(), nullable=False),
    sa.Column('cust_code', sa.String(length=100), nullable=True),
    sa.Column('ok_flag', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('source_sequence', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'ser_nr', name='uq_hansa_delivery_headers_company_sernr')
    )
    op.create_index(op.f('ix_hansa_delivery_headers_cust_code'), 'hansa_delivery_headers', ['cust_code'], unique=False)
    op.create_index(op.f('ix_hansa_delivery_headers_id'), 'hansa_delivery_headers', ['id'], unique=False)
    op.create_index(op.f('ix_hansa_delivery_headers_location'), 'hansa_delivery_headers', ['location'], unique=False)
    op.create_index(op.f('ix_hansa_delivery_headers_order_nr'), 'hansa_delivery_headers', ['order_nr'], unique=False)
    op.create_index(op.f('ix_hansa_delivery_headers_ser_nr'), 'hansa_delivery_headers', ['ser_nr'], unique=False)
    op.create_index(op.f('ix_hansa_delivery_headers_ship_date'), 'hansa_delivery_headers', ['ship_date'], unique=False)
    op.create_table('hansa_delivery_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('ser_nr', sa.String(length=100), nullable=False),
    sa.Column('row_number', sa.String(length=50), nullable=False),
    sa.Column('art_code', sa.String(length=100), nullable=True),
    sa.Column('ship', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('source_row_hash', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'ser_nr', 'row_number', name='uq_hansa_delivery_lines_company_sernr_row'),
    sa.UniqueConstraint('company_no', 'source_row_hash', name='uq_hansa_delivery_lines_source_hash')
    )
    op.create_index(op.f('ix_hansa_delivery_lines_art_code'), 'hansa_delivery_lines', ['art_code'], unique=False)
    op.create_index(op.f('ix_hansa_delivery_lines_id'), 'hansa_delivery_lines', ['id'], unique=False)
    op.create_index(op.f('ix_hansa_delivery_lines_location'), 'hansa_delivery_lines', ['location'], unique=False)
    op.create_index(op.f('ix_hansa_delivery_lines_ser_nr'), 'hansa_delivery_lines', ['ser_nr'], unique=False)
    op.create_index(op.f('ix_hansa_delivery_lines_source_row_hash'), 'hansa_delivery_lines', ['source_row_hash'], unique=False)
    op.create_table('hansa_invoice_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('ser_nr', sa.String(length=100), nullable=False),
    sa.Column('inv_date', sa.Date(), nullable=False),
    sa.Column('cust_code', sa.String(length=100), nullable=True),
    sa.Column('pay_deal', sa.String(length=50), nullable=True),
    sa.Column('ok_flag', sa.Integer(), nullable=True),
    sa.Column('inv_type', sa.String(length=50), nullable=True),
    sa.Column('cred_mark', sa.String(length=50), nullable=True),
    sa.Column('sales_man', sa.String(length=100), nullable=True),
    sa.Column('upd_stock_flag', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('source_sequence', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'ser_nr', name='uq_hansa_invoice_headers_company_sernr')
    )
    op.create_index(op.f('ix_hansa_invoice_headers_cust_code'), 'hansa_invoice_headers', ['cust_code'], unique=False)
    op.create_index(op.f('ix_hansa_invoice_headers_id'), 'hansa_invoice_headers', ['id'], unique=False)
    op.create_index(op.f('ix_hansa_invoice_headers_inv_date'), 'hansa_invoice_headers', ['inv_date'], unique=False)
    op.create_index(op.f('ix_hansa_invoice_headers_location'), 'hansa_invoice_headers', ['location'], unique=False)
    op.create_index(op.f('ix_hansa_invoice_headers_sales_man'), 'hansa_invoice_headers', ['sales_man'], unique=False)
    op.create_index(op.f('ix_hansa_invoice_headers_ser_nr'), 'hansa_invoice_headers', ['ser_nr'], unique=False)
    op.create_table('hansa_invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('ser_nr', sa.String(length=100), nullable=False),
    sa.Column('row_number', sa.String(length=50), nullable=False),
    sa.Column('art_code', sa.String(length=100), nullable=True),
    sa.Column('quant', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('not_upd_stock_flag', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('source_row_hash', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'ser_nr', 'row_number', name='uq_hansa_invoice_lines_company_sernr_row'),
    sa.UniqueConstraint('company_no', 'source_row_hash', name='uq_hansa_invoice_lines_source_hash')
    )
    op.create_index(op.f('ix_hansa_invoice_lines_art_code'), 'hansa_invoice_lines', ['art_code'], unique=False)
    op.create_index(op.f('ix_hansa_invoice_lines_id'), 'hansa_invoice_lines', ['id'], unique=False)
    op.create_index(op.f('ix_hansa_invoice_lines_location'), 'hansa_invoice_lines', ['location'], unique=False)
    op.create_index(op.f('ix_hansa_invoice_lines_ser_nr'), 'hansa_invoice_lines', ['ser_nr'], unique=False)
    op.create_index(op.f('ix_hansa_invoice_lines_source_row_hash'), 'hansa_invoice_lines', ['source_row_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hansa_invoice_lines_source_row_hash'), table_name='hansa_invoice_lines')
    op.drop_index(op.f('ix_hansa_invoice_lines_ser_nr'), table_name='hansa_invoice_lines')
    op.drop_index(op.f('ix_hansa_invoice_lines_location'), table_name='hansa_invoice_lines')
    op.drop_index(op.f('ix_hansa_invoice_lines_id'), table_name='hansa_invoice_lines')
    op.drop_index(op.f('ix_hansa_invoice_lines_art_code'), table_name='hansa_invoice_lines')
    op.drop_table('hansa_invoice_lines')
    op.drop_index(op.f('ix_hansa_invoice_headers_ser_nr'), table_name='hansa_invoice_headers')
    op.drop_index(op.f('ix_hansa_invoice_headers_sales_man'), table_name='hansa_invoice_headers')
    op.drop_index(op.f('ix_hansa_invoice_headers_location'), table_name='hansa_invoice_headers')
    op.drop_index(op.f('ix_hansa_invoice_headers_inv_date'), table_name='hansa_invoice_headers')
    op.drop_index(op.f('ix_hansa_invoice_headers_id'), table_name='hansa_invoice_headers')
    op.drop_index(op.f('ix_hansa_invoice_headers_cust_code'), table_name='hansa_invoice_headers')
    op.drop_table('hansa_invoice_headers')
    op.drop_index(op.f('ix_hansa_delivery_lines_source_row_hash'), table_name='hansa_delivery_lines')
    op.drop_index(op.f('ix_hansa_delivery_lines_ser_nr'), table_name='hansa_delivery_lines')
    op.drop_index(op.f('ix_hansa_delivery_lines_location'), table_name='hansa_delivery_lines')
    op.drop_index(op.f('ix_hansa_delivery_lines_id'), table_name='hansa_delivery_lines')
    op.drop_index(op.f('ix_hansa_delivery_lines_art_code'), table_name='hansa_delivery_lines')
    op.drop_table('hansa_delivery_lines')
    op.drop_index(op.f('ix_hansa_delivery_headers_ship_date'), table_name='hansa_delivery_headers')
    op.drop_index(op.f('ix_hansa_delivery_headers_ser_nr'), table_name='hansa_delivery_headers')
    op.drop_index(op.f('ix_hansa_delivery_headers_order_nr'), table_name='hansa_delivery_headers')
    op.drop_index(op.f('ix_hansa_delivery_headers_location'), table_name='hansa_delivery_headers')
    op.drop_index(op.f('ix_hansa_delivery_headers_id'), table_name='hansa_delivery_headers')
    op.drop_index(op.f('ix_hansa_delivery_headers_cust_code'), table_name='hansa_delivery_headers')
    op.drop_table('hansa_delivery_headers')
    op.drop_index(op.f('ix_fact_sales_lines_transaction_date'), table_name='fact_sales_lines')
    op.drop_index(op.f('ix_fact_sales_lines_source_type'), table_name='fact_sales_lines')
    op.drop_index(op.f('ix_fact_sales_lines_source_row_hash'), table_name='fact_sales_lines')
    op.drop_index(op.f('ix_fact_sales_lines_source_no'), table_name='fact_sales_lines')
    op.drop_index(op.f('ix_fact_sales_lines_salesperson'), table_name='fact_sales_lines')
    op.drop_index(op.f('ix_fact_sales_lines_location'), table_name='fact_sales_lines')
    op.drop_index(op.f('ix_fact_sales_lines_item_group_code'), table_name='fact_sales_lines')
    op.drop_index(op.f('ix_fact_sales_lines_item_code'), table_name='fact_sales_lines')
    op.drop_index(op.f('ix_fact_sales_lines_id'), table_name='fact_sales_lines')
    op.drop_index(op.f('ix_fact_sales_lines_customer_code'), table_name='fact_sales_lines')
    op.drop_table('fact_sales_lines')
    # ### end Alembic commands ###
