"""phase1_financial_intelligence_expansion

Revision ID: 65d9b37e342b
Revises: bb7e1faf463b
Create Date: 2026-06-07 17:23:09.672251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d9b37e342b'
down_revision: Union[str, Sequence[str], None] = 'bb7e1faf463b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gl_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('acc_number', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('acc_type', sa.Integer(), nullable=True),
    sa.Column('curncy', sa.String(length=20), nullable=True),
    sa.Column('group_acc', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'acc_number', name='uq_gl_accounts_company_accnr')
    )
    op.create_index(op.f('ix_gl_accounts_acc_number'), 'gl_accounts', ['acc_number'], unique=False)
    op.create_index(op.f('ix_gl_accounts_acc_type'), 'gl_accounts', ['acc_type'], unique=False)
    op.create_index(op.f('ix_gl_accounts_group_acc'), 'gl_accounts', ['group_acc'], unique=False)
    op.create_index(op.f('ix_gl_accounts_id'), 'gl_accounts', ['id'], unique=False)
    op.create_table('hansa_order_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('ser_nr', sa.String(length=100), nullable=False),
    sa.Column('cust_code', sa.String(length=100), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('sales_man', sa.String(length=100), nullable=True),
    sa.Column('ok_flag', sa.Integer(), nullable=True),
    sa.Column('currency_code', sa.String(length=20), nullable=True),
    sa.Column('pay_deal', sa.String(length=50), nullable=True),
    sa.Column('sum1', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sum4', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('base_sum4', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_sequence', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'ser_nr', name='uq_hansa_order_headers_company_sernr')
    )
    op.create_index(op.f('ix_hansa_order_headers_company_no'), 'hansa_order_headers', ['company_no'], unique=False)
    op.create_index(op.f('ix_hansa_order_headers_cust_code'), 'hansa_order_headers', ['cust_code'], unique=False)
    op.create_index(op.f('ix_hansa_order_headers_id'), 'hansa_order_headers', ['id'], unique=False)
    op.create_index(op.f('ix_hansa_order_headers_order_date'), 'hansa_order_headers', ['order_date'], unique=False)
    op.create_index(op.f('ix_hansa_order_headers_sales_man'), 'hansa_order_headers', ['sales_man'], unique=False)
    op.create_index(op.f('ix_hansa_order_headers_ser_nr'), 'hansa_order_headers', ['ser_nr'], unique=False)
    op.create_table('hansa_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('ser_nr', sa.String(length=100), nullable=False),
    sa.Column('row_number', sa.String(length=50), nullable=False),
    sa.Column('art_code', sa.String(length=100), nullable=True),
    sa.Column('quant', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('disc', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_row_hash', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'ser_nr', 'row_number', name='uq_hansa_order_lines_company_sernr_row'),
    sa.UniqueConstraint('company_no', 'source_row_hash', name='uq_hansa_order_lines_source_hash')
    )
    op.create_index(op.f('ix_hansa_order_lines_art_code'), 'hansa_order_lines', ['art_code'], unique=False)
    op.create_index(op.f('ix_hansa_order_lines_company_no'), 'hansa_order_lines', ['company_no'], unique=False)
    op.create_index(op.f('ix_hansa_order_lines_id'), 'hansa_order_lines', ['id'], unique=False)
    op.create_index(op.f('ix_hansa_order_lines_ser_nr'), 'hansa_order_lines', ['ser_nr'], unique=False)
    op.create_index(op.f('ix_hansa_order_lines_source_row_hash'), 'hansa_order_lines', ['source_row_hash'], unique=False)
    op.create_table('hansa_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('ser_nr', sa.String(length=100), nullable=False),
    sa.Column('cust_code', sa.String(length=100), nullable=True),
    sa.Column('trans_date', sa.Date(), nullable=True),
    sa.Column('invoice_nr', sa.String(length=100), nullable=True),
    sa.Column('inv_curncy', sa.String(length=20), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('rec_curncy', sa.String(length=20), nullable=True),
    sa.Column('rec_val', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ok_flag', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'ser_nr', name='uq_hansa_receipts_company_sernr')
    )
    op.create_index(op.f('ix_hansa_receipts_company_no'), 'hansa_receipts', ['company_no'], unique=False)
    op.create_index(op.f('ix_hansa_receipts_cust_code'), 'hansa_receipts', ['cust_code'], unique=False)
    op.create_index(op.f('ix_hansa_receipts_id'), 'hansa_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_hansa_receipts_invoice_nr'), 'hansa_receipts', ['invoice_nr'], unique=False)
    op.create_index(op.f('ix_hansa_receipts_ser_nr'), 'hansa_receipts', ['ser_nr'], unique=False)
    op.create_index(op.f('ix_hansa_receipts_trans_date'), 'hansa_receipts', ['trans_date'], unique=False)
    op.add_column('hansa_invoice_headers', sa.Column('pay_date', sa.Date(), nullable=True))
    op.add_column('hansa_invoice_headers', sa.Column('pay_days', sa.Integer(), nullable=True))
    op.add_column('hansa_invoice_headers', sa.Column('currency_code', sa.String(length=20), nullable=True))
    op.add_column('hansa_invoice_headers', sa.Column('cred_inv', sa.String(length=100), nullable=True))
    op.add_column('hansa_invoice_headers', sa.Column('sum1', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('hansa_invoice_headers', sa.Column('sum4', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('hansa_invoice_headers', sa.Column('base_sum4', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('refresh_settings', sa.Column('include_orders', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('refresh_settings', sa.Column('include_receipts', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('refresh_settings', sa.Column('include_gl_accounts', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_settings', 'include_gl_accounts')
    op.drop_column('refresh_settings', 'include_receipts')
    op.drop_column('refresh_settings', 'include_orders')
    op.drop_column('hansa_invoice_headers', 'base_sum4')
    op.drop_column('hansa_invoice_headers', 'sum4')
    op.drop_column('hansa_invoice_headers', 'sum1')
    op.drop_column('hansa_invoice_headers', 'cred_inv')
    op.drop_column('hansa_invoice_headers', 'currency_code')
    op.drop_column('hansa_invoice_headers', 'pay_days')
    op.drop_column('hansa_invoice_headers', 'pay_date')
    op.drop_index(op.f('ix_hansa_receipts_trans_date'), table_name='hansa_receipts')
    op.drop_index(op.f('ix_hansa_receipts_ser_nr'), table_name='hansa_receipts')
    op.drop_index(op.f('ix_hansa_receipts_invoice_nr'), table_name='hansa_receipts')
    op.drop_index(op.f('ix_hansa_receipts_id'), table_name='hansa_receipts')
    op.drop_index(op.f('ix_hansa_receipts_cust_code'), table_name='hansa_receipts')
    op.drop_index(op.f('ix_hansa_receipts_company_no'), table_name='hansa_receipts')
    op.drop_table('hansa_receipts')
    op.drop_index(op.f('ix_hansa_order_lines_source_row_hash'), table_name='hansa_order_lines')
    op.drop_index(op.f('ix_hansa_order_lines_ser_nr'), table_name='hansa_order_lines')
    op.drop_index(op.f('ix_hansa_order_lines_id'), table_name='hansa_order_lines')
    op.drop_index(op.f('ix_hansa_order_lines_company_no'), table_name='hansa_order_lines')
    op.drop_index(op.f('ix_hansa_order_lines_art_code'), table_name='hansa_order_lines')
    op.drop_table('hansa_order_lines')
    op.drop_index(op.f('ix_hansa_order_headers_ser_nr'), table_name='hansa_order_headers')
    op.drop_index(op.f('ix_hansa_order_headers_sales_man'), table_name='hansa_order_headers')
    op.drop_index(op.f('ix_hansa_order_headers_order_date'), table_name='hansa_order_headers')
    op.drop_index(op.f('ix_hansa_order_headers_id'), table_name='hansa_order_headers')
    op.drop_index(op.f('ix_hansa_order_headers_cust_code'), table_name='hansa_order_headers')
    op.drop_index(op.f('ix_hansa_order_headers_company_no'), table_name='hansa_order_headers')
    op.drop_table('hansa_order_headers')
    op.drop_index(op.f('ix_gl_accounts_id'), table_name='gl_accounts')
    op.drop_index(op.f('ix_gl_accounts_group_acc'), table_name='gl_accounts')
    op.drop_index(op.f('ix_gl_accounts_acc_type'), table_name='gl_accounts')
    op.drop_index(op.f('ix_gl_accounts_acc_number'), table_name='gl_accounts')
    op.drop_table('gl_accounts')
    # ### end Alembic commands ###
