"""create initial reporting tables

Revision ID: 71ee809d6b6c
Revises: 
Create Date: 2026-06-01 10:16:12.534589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ee809d6b6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cu_type', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'code', name='uq_customers_company_code')
    )
    op.create_index(op.f('ix_customers_code'), 'customers', ['code'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('item_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'code', name='uq_item_groups_company_code')
    )
    op.create_index(op.f('ix_item_groups_code'), 'item_groups', ['code'], unique=False)
    op.create_index(op.f('ix_item_groups_id'), 'item_groups', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('alternative_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('item_group_code', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unit_coefficient', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'code', name='uq_items_company_code')
    )
    op.create_index(op.f('ix_items_alternative_code'), 'items', ['alternative_code'], unique=False)
    op.create_index(op.f('ix_items_code'), 'items', ['code'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_item_group_code'), 'items', ['item_group_code'], unique=False)
    op.create_table('refresh_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('refresh_type', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_runs_id'), 'refresh_runs', ['id'], unique=False)
    op.create_table('sales_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_no', sa.String(length=100), nullable=False),
    sa.Column('source_row_hash', sa.String(length=255), nullable=False),
    sa.Column('order_no', sa.String(length=100), nullable=True),
    sa.Column('customer_code', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('item_group_code', sa.String(length=100), nullable=True),
    sa.Column('item_group_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('salesperson', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_weight', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('item_weight', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unit_coefficient', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tonnes', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('pay_deal', sa.String(length=50), nullable=True),
    sa.Column('credit_mark', sa.String(length=50), nullable=True),
    sa.Column('invoice_type', sa.String(length=50), nullable=True),
    sa.Column('ok_flag', sa.Integer(), nullable=True),
    sa.Column('upd_stock_flag', sa.Integer(), nullable=True),
    sa.Column('not_upd_stock_flag', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'source_type', 'source_row_hash', name='uq_sales_transactions_source_row_hash')
    )
    op.create_index(op.f('ix_sales_transactions_customer_code'), 'sales_transactions', ['customer_code'], unique=False)
    op.create_index(op.f('ix_sales_transactions_id'), 'sales_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_sales_transactions_item_code'), 'sales_transactions', ['item_code'], unique=False)
    op.create_index(op.f('ix_sales_transactions_item_group_code'), 'sales_transactions', ['item_group_code'], unique=False)
    op.create_index(op.f('ix_sales_transactions_location'), 'sales_transactions', ['location'], unique=False)
    op.create_index(op.f('ix_sales_transactions_salesperson'), 'sales_transactions', ['salesperson'], unique=False)
    op.create_index(op.f('ix_sales_transactions_source_no'), 'sales_transactions', ['source_no'], unique=False)
    op.create_index(op.f('ix_sales_transactions_source_row_hash'), 'sales_transactions', ['source_row_hash'], unique=False)
    op.create_index(op.f('ix_sales_transactions_source_type'), 'sales_transactions', ['source_type'], unique=False)
    op.create_index(op.f('ix_sales_transactions_transaction_date'), 'sales_transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_transactions_transaction_date'), table_name='sales_transactions')
    op.drop_index(op.f('ix_sales_transactions_source_type'), table_name='sales_transactions')
    op.drop_index(op.f('ix_sales_transactions_source_row_hash'), table_name='sales_transactions')
    op.drop_index(op.f('ix_sales_transactions_source_no'), table_name='sales_transactions')
    op.drop_index(op.f('ix_sales_transactions_salesperson'), table_name='sales_transactions')
    op.drop_index(op.f('ix_sales_transactions_location'), table_name='sales_transactions')
    op.drop_index(op.f('ix_sales_transactions_item_group_code'), table_name='sales_transactions')
    op.drop_index(op.f('ix_sales_transactions_item_code'), table_name='sales_transactions')
    op.drop_index(op.f('ix_sales_transactions_id'), table_name='sales_transactions')
    op.drop_index(op.f('ix_sales_transactions_customer_code'), table_name='sales_transactions')
    op.drop_table('sales_transactions')
    op.drop_index(op.f('ix_refresh_runs_id'), table_name='refresh_runs')
    op.drop_table('refresh_runs')
    op.drop_index(op.f('ix_items_item_group_code'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_code'), table_name='items')
    op.drop_index(op.f('ix_items_alternative_code'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_item_groups_id'), table_name='item_groups')
    op.drop_index(op.f('ix_item_groups_code'), table_name='item_groups')
    op.drop_table('item_groups')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_code'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
