"""add_schedule_fields_and_refresh_jobs

Revision ID: bb7e1faf463b
Revises: a2b3c4d5e6f7
Create Date: 2026-06-07 08:25:06.577311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb7e1faf463b'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('companies', sa.JSON(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_jobs_id'), 'refresh_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_jobs_job_id'), 'refresh_jobs', ['job_id'], unique=True)
    op.drop_index(op.f('ix_fsl_company_customer_date'), table_name='fact_sales_lines')
    op.drop_index(op.f('ix_fsl_company_date'), table_name='fact_sales_lines')
    op.drop_index(op.f('ix_fsl_company_group_date'), table_name='fact_sales_lines')
    op.drop_index(op.f('ix_fsl_company_salesperson_date'), table_name='fact_sales_lines')
    op.alter_column('item_stock_status', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_item_stock_art_code'), table_name='item_stock_status')
    op.drop_index(op.f('ix_item_stock_company_no'), table_name='item_stock_status')
    op.drop_index(op.f('ix_item_stock_group_code'), table_name='item_stock_status')
    op.drop_index(op.f('ix_item_stock_location'), table_name='item_stock_status')
    op.create_index(op.f('ix_item_stock_status_art_code'), 'item_stock_status', ['art_code'], unique=False)
    op.create_index(op.f('ix_item_stock_status_company_no'), 'item_stock_status', ['company_no'], unique=False)
    op.create_index(op.f('ix_item_stock_status_id'), 'item_stock_status', ['id'], unique=False)
    op.create_index(op.f('ix_item_stock_status_item_group_code'), 'item_stock_status', ['item_group_code'], unique=False)
    op.create_index(op.f('ix_item_stock_status_location'), 'item_stock_status', ['location'], unique=False)
    op.add_column('refresh_settings', sa.Column('schedule_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('refresh_settings', sa.Column('schedule_frequency', sa.String(length=20), nullable=False, server_default=sa.text("'daily'")))
    op.add_column('refresh_settings', sa.Column('schedule_time', sa.String(length=10), nullable=False, server_default=sa.text("'02:00'")))
    op.create_index(op.f('ix_refresh_settings_id'), 'refresh_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_settings_id'), table_name='refresh_settings')
    op.drop_column('refresh_settings', 'schedule_time')
    op.drop_column('refresh_settings', 'schedule_frequency')
    op.drop_column('refresh_settings', 'schedule_enabled')
    op.drop_index(op.f('ix_item_stock_status_location'), table_name='item_stock_status')
    op.drop_index(op.f('ix_item_stock_status_item_group_code'), table_name='item_stock_status')
    op.drop_index(op.f('ix_item_stock_status_id'), table_name='item_stock_status')
    op.drop_index(op.f('ix_item_stock_status_company_no'), table_name='item_stock_status')
    op.drop_index(op.f('ix_item_stock_status_art_code'), table_name='item_stock_status')
    op.create_index(op.f('ix_item_stock_location'), 'item_stock_status', ['location'], unique=False)
    op.create_index(op.f('ix_item_stock_group_code'), 'item_stock_status', ['item_group_code'], unique=False)
    op.create_index(op.f('ix_item_stock_company_no'), 'item_stock_status', ['company_no'], unique=False)
    op.create_index(op.f('ix_item_stock_art_code'), 'item_stock_status', ['art_code'], unique=False)
    op.alter_column('item_stock_status', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_fsl_company_salesperson_date'), 'fact_sales_lines', ['company_no', 'salesperson', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_fsl_company_group_date'), 'fact_sales_lines', ['company_no', 'item_group_code', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_fsl_company_date'), 'fact_sales_lines', ['company_no', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_fsl_company_customer_date'), 'fact_sales_lines', ['company_no', 'customer_code', 'transaction_date'], unique=False)
    op.drop_index(op.f('ix_refresh_jobs_job_id'), table_name='refresh_jobs')
    op.drop_index(op.f('ix_refresh_jobs_id'), table_name='refresh_jobs')
    op.drop_table('refresh_jobs')
    # ### end Alembic commands ###
