"""add customer product group movement

Revision ID: dfd50e6be323
Revises: 71ee809d6b6c
Create Date: 2026-06-01 13:26:12.003631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd50e6be323'
down_revision: Union[str, Sequence[str], None] = '71ee809d6b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_product_group_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_no', sa.String(length=20), nullable=False),
    sa.Column('customer_code', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('product_group_code', sa.String(length=100), nullable=False),
    sa.Column('product_group_name', sa.String(length=255), nullable=True),
    sa.Column('buying_months_6m', sa.Integer(), nullable=False),
    sa.Column('recent_buying_months_3m', sa.Integer(), nullable=False),
    sa.Column('avg_monthly_tonnes_6m', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_month_tonnes', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('expected_mtd_tonnes', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tonnage_gap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('gap_percent', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('last_purchase_date', sa.Date(), nullable=True),
    sa.Column('days_since_last_purchase', sa.Integer(), nullable=True),
    sa.Column('last_salesperson', sa.String(length=100), nullable=True),
    sa.Column('last_location', sa.String(length=100), nullable=True),
    sa.Column('buyer_status', sa.String(length=100), nullable=True),
    sa.Column('action_band', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'customer_code', 'product_group_code', name='uq_customer_product_group_movement')
    )
    op.create_index(op.f('ix_customer_product_group_movement_action_band'), 'customer_product_group_movement', ['action_band'], unique=False)
    op.create_index(op.f('ix_customer_product_group_movement_buyer_status'), 'customer_product_group_movement', ['buyer_status'], unique=False)
    op.create_index(op.f('ix_customer_product_group_movement_customer_code'), 'customer_product_group_movement', ['customer_code'], unique=False)
    op.create_index(op.f('ix_customer_product_group_movement_id'), 'customer_product_group_movement', ['id'], unique=False)
    op.create_index(op.f('ix_customer_product_group_movement_product_group_code'), 'customer_product_group_movement', ['product_group_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_product_group_movement_product_group_code'), table_name='customer_product_group_movement')
    op.drop_index(op.f('ix_customer_product_group_movement_id'), table_name='customer_product_group_movement')
    op.drop_index(op.f('ix_customer_product_group_movement_customer_code'), table_name='customer_product_group_movement')
    op.drop_index(op.f('ix_customer_product_group_movement_buyer_status'), table_name='customer_product_group_movement')
    op.drop_index(op.f('ix_customer_product_group_movement_action_band'), table_name='customer_product_group_movement')
    op.drop_table('customer_product_group_movement')
    # ### end Alembic commands ###
